#pragma once

#define TAPPING_TERM 220
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 175
#define QUICK_TAP_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define RETRO_TAPPING_PER_KEY
#define FLOW_TAP_TERM 150
#define CHORDAL_HOLD
